server:
  port: 8080

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:

      routes:
        - id: service1
          uri: lb://SERVICE1
          predicates:
            - Path=/service1/**
        - id: service2
          uri: lb://SERVICE2
          predicates:
            - Path=/service-2/**

management:
  endpoint:
    gateway:
      enabled: true

  endpoints:
    web:
      exposure:
        include: gateway
